name: Fetch and publish announcements

on:
    push:
        branches:
            - master
    schedule:
        # https://crontab.guru
        - cron: "34 */4 * * 1-5"
        - cron: "52 */8 * * 0,6"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 16.x
              uses: actions/setup-node@master
              with:
                  node-version: 16
                  cache: "yarn"
            - name: Cache apify_storage
              uses: actions/cache@v2
              with:
                  path: |
                      ./apify_storage
                  key: v1-apify-storage
            - name: Retrieving dependencies
              run: yarn
            - name: Build crawler
              run: yarn build
            - name: Initiate INPUT store
              run: |
                  mkdir -p ./apify_storage/key_value_stores/default
                  cat << EOF > ./apify_storage/key_value_stores/default/INPUT.json
                  {
                      "$schema": "../../../INPUT_SCHEMA.json",
                      "smhsUrl": "https://www.smhs.kh.edu.tw"
                  }
                  EOF
            - name: Start crawler
              run: yarn start:prod
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: data
                  destination-github-username: smhs-os-project
                  destination-repository-name: smhs-announcements
                  user-name: schweb-crawler
                  user-email: sw@imych.one
                  target-branch: master
                  commit-message: update announcement
